theme: jekyll-theme-slate
title: Mark A. Conley
markdown: kramdown
email: conley@psych.columbia.edu
description: I am a PhD student in Psychology at Columbia University.  Using primarily field experiments, I manipulate the fundamental motivations which cause socially significant behaviors. 
twitter_username: mactiv8
github_username:  mac2393
avatar: https://github.com/mac2393/mac2393.github.io/blob/master/codercat.jpg
