theme: jekyll-theme-slate
title: Mark A. Conley
markdown: kramdown
email: mark.conley@hhs.se
description: I am an Assistant Professor at the Stockholm School of Economics. I study motivation in Entrepreneurship and Innovation. I am either conducting a field experiment or trying to. 
twitter_username: mactiv8
github_username:  mac2393
avatar:
